invoice/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('invoice.views',
        url(ur'^generate/(?P<invoice_id>\w+)/key/(?P<key>\w{30})/$', 'generate'),
        url(ur'^$', 'index'),
        url(ur'^create/$', 'create', name="create"),
)

technetium/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'technetium.views.home', name='home'),
    # url(r'^technetium/', include('technetium.foo.urls')),
    url(ur'^login/$', 'django.contrib.auth.views.login'),
    url(ur'^logout/$', 'django.contrib.auth.views.logout_then_login'),
    
    url(ur'^$', 'technetium.views.index'),
    url(ur'^dashboard/$', 'technetium.views.dashboard'),

    url(ur'^invoice/', include('invoice.urls')),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(ur'^admin/', include(admin.site.urls)),
)

invoice/models.py
import string
import random

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Item(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=10)

    def __unicode__(self):
        return "<Item n:%s p:%s>" % (self.name, self.price)

class InvoiceItem(models.Model):
    user = models.ForeignKey(User)
    item = models.ForeignKey(Item)
    count = models.DecimalField(decimal_places=2, max_digits=10)
    cost = models.DecimalField(decimal_places=2, max_digits=10, blank=True,
            null=True)

    def __unicode__(self):
        return "<InvoiceItem i:%s #:%s c:%s>" %(self.item, self.count, self.cost)
    
    def save(self, *a, **kw):
        self.cost = float(self.item.price) * float(self.count)
        super(InvoiceItem, self).save(*a, **kw)

class Invoice(models.Model):
    user = models.ForeignKey(User)
    bill_to = models.TextField()
    items = models.ManyToManyField(InvoiceItem)
    date = models.DateTimeField()
    total = models.DecimalField(decimal_places=2, max_digits=10, blank=True,
            null=True)
    secret_key = models.CharField(max_length=30, blank=True, null=True)

    def __unicode__(self):
        return "<Invoice b:%s d:%s t:%s>" % (self.bill_to, self.date, self.total)

    def save(self, *a, **kw):
        if self.secret_key is None:
            self.secret_key = ''.join([random.choice(
                    string.digits+string.ascii_uppercase+string.ascii_lowercase
                ) for x in range(0,30)])
        super(Invoice, self).save(*a, **kw)
        self.total = sum([item.cost for item in self.items.all()])
        super(Invoice, self).save(*a, **kw)

class Profile(models.Model):
    user = models.OneToOneField(User)
    info = models.TextField()

technetium/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    billing_info = models.TextField()

invoice/forms.py
from django import forms
from django.forms.formsets import formset_factory
import datetime

class InvoiceForm(forms.Form):
    bill_to = forms.CharField(widget=forms.Textarea)
    date = forms.DateField(initial=datetime.date.today)

class ItemForm(forms.Form):
    item_name = forms.CharField()
    item_count = forms.DecimalField()
    item_price = forms.DecimalField()

ItemFormSet = formset_factory(ItemForm)

invoice/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden

from invoice.models import Invoice, InvoiceItem, Item
from invoice.forms import InvoiceForm, ItemFormSet

def generate(request, invoice_id, key):
    invoice = get_object_or_404(Invoice, id=invoice_id)
    if invoice.secret_key == key:
        return render(request, 'invoice/invoice.html', {'invoice': invoice})
    else:
        raise HttpResponseForbidden

@login_required
def index(request):
    invoices = Invoice.objects.filter(user=request.user)
    return render(request, 'invoice/index.html', {'invoices': invoices})

@login_required
def create(request):
    if request.method == 'POST':
        invoice_form = InvoiceForm(request.POST)
        item_formset = ItemFormSet(request.POST) 
        if invoice_form.is_valid() and item_formset.is_valid():
            invoice_form.clean()
            item_formset.clean()
            new_invoice = Invoice(bill_to=invoice_form['bill_to'].data,
                    date=invoice_form['date'].data, user=request.user)
            new_invoice.save()
            for form in item_formset:
                print form.cleaned_data
                print form['item_price'].data
                new_item = Item(name=form['item_name'].data,
                    price=form['item_price'].data, user=request.user)
                new_item.save()
                print type(new_item.price)
                new_invoice_item = InvoiceItem(count=form['item_count'].data,
                        item=new_item, user=request.user)
                new_invoice_item.save()
                new_invoice.items.add(new_invoice_item)
            new_invoice.save()
            return redirect('/dashboard/') 
    else:
        invoice_form = InvoiceForm()
        item_formset = ItemFormSet()
    return render(request, 'invoice/create.html', {'invoice_form': invoice_form,
                                'item_formset': item_formset,
                                'form_counter': len(item_formset.forms) - 1,})

technetium/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'index.html')

@login_required
def dashboard(request):
    return render(request, 'dashboard.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/main.css" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
  </head>
  <body>
    <div id="navi" class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <ul class="nav">
          <li><a href="/">home</a></li>
          <li><a href="/invoice/">invoice</a></li>
          {% if user.is_authenticated %}<li><a href="/logout/">logout</a></li>{% endif %}
        </ul>
        <a class="brand" href="/">technetium</a>
        {% if not user.is_authenticated %}<form class="form-horizontal" action="/login/" method="post">
          {% csrf_token %}
          <input type="text" placeholder="username" name="username" />
          <input type="password" placeholder="password" name="password" />
          <button class="btn" type="submit">login</button>
        </form>{% endif %}
      </div>
    </div>
    <div id="boxxy" class="container">
      {% block content %}{% endblock %}
    </div>
    </div>
  </body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% block title %}dashboard{% endblock %}
{% block content %}
welcome!
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}technetium{% endblock %}
{% block content %}
<h1>technetium</h1>
{% endblock %}

templates/invoice/create.html
{% extends "base.html" %}
{% block title %}create an invoice{% endblock %}
{% block content %}
<script language="javascript">
  form_counter = {{ form_counter }};
  function add_item() {
    form_counter++;
    $("#add_item").before('<input type="text" name="form-'+form_counter+'-item_count" placeholder="#"/> \
                           <input type="text" name="form-'+form_counter+'-item_name" placeholder="description" /> \
                           <input type="text" name="form-'+form_counter+'-item_price" placeholder="$$" /><br />'
                           );
    $("#id_form-TOTAL_FORMS").attr('value', form_counter + 1);
  }
</script>

<form action="." method="POST">
  {% csrf_token %}
  <label for="id_bill_to">Bill to:</label>{{ invoice_form.bill_to }}
  <label for="id_date">Date:</label>{{ invoice_form.date }}
  <label>Items</label>
  {{ item_formset.management_form }}
  {% for form in item_formset %}
  <input type="text" name="form-{{ forloop.counter0 }}-item_count" placeholder="#" />
  <input type="text" name="form-{{ forloop.counter0 }}-item_name" placeholder="description" />
  <input type="text" name="form-{{ forloop.counter0 }}-item_price" placeholder="$$" /><br />
  {% endfor %}
  <a id="add_item" onclick="javascript:add_item();">add item</a><br />
  <button class="btn" type="submit" id="submit_btn">create</button>
</form>
{% endblock %}

templates/invoice/index.html
{% extends "base.html" %}
{% block title %}invoices{% endblock %}
{% block content %}
<table class="span12 table-striped">
  <thead>
  </thead>
  <tbody>
    {% for invoice in invoices %}
    <tr>
      <td>{{ invoice.bill_to|linebreaks }}</td>
      <td>{{ invoice.date }}</td>
      <td>{{ invoice.total }}</td>
      <td><a href="{% url invoice.views.generate invoice.pk invoice.secret_key %}">View</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/invoice/invoice.html
<!DOCTYPE html>
<html>
  <head>
    <title>Invoice - {{ invoice.date|date:"Y-m-d" }}</title>
    <link rel="stylesheet" href="/static/style.css" type="text/css" />
  </head>
  <body>
    <div id="container">
      <div id="info">{{ invoice.user.get_profile.billing_info|linebreaks }}</div>
      <div id="billto">Bill to:<br />
        {{ invoice.bill_to|linebreaks }}
      </div>
      <table id="bill">
        <thead>
          <tr>
            <td>Item</td>
            <td>Unit Price</td>
            <td>Quantity</td>
            <td>Amount</td>
          </tr>
        </thead>
        <tbody>
          {% for item in invoice.items.all %}
          <tr>
            <td>{{ item.item.name }}</td>
            <td>{{ item.item.price }}</td>
            <td>{{ item.count }}</td>
            <td class="amount">{{ item.cost }}</td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan="3">Total</td>
            <td class="total">{{ invoice.total }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </body>
</html>